authapp/urls.py
# from django.conf.urls import url

import authapp.views as authapp
from django.urls import re_path

app_name="authapp"

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^edit/$', authapp.edit, name='edit'),
    re_path('verify/<email>/<key>/', authapp.verify, name='verify'),
    ]

    

geekshop/urls.py
# from django.conf.urls import *
from django.contrib import admin
import mainapp.views as mainapp

from django.conf import settings
from django.conf.urls.static import static

from django.urls import re_path, path, include

urlpatterns = [
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^products/', include('mainapp.urls', namespace='products')),
    re_path(r'^contact/', mainapp.contact, name='contact'),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
    re_path(r'^admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
# from django.conf.urls import url

import ordersapp.views as ordersapp
from django.urls import path

app_name="ordersapp"

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='list'),
    path('create/', ordersapp.OrderCreate.as_view(), name='create'),
    path('update/<pk>/', ordersapp.OrderUpdate.as_view(), name='update'),
    path('delete/<pk>/', ordersapp.OrderDelete.as_view(), name='delete'),
    path('read/<pk>/', ordersapp.OrderRead.as_view(), name='read'),
    path('forming/complete/<pk>/', ordersapp.forming_complete, name='forming_complete'),

    path('payment/result/', ordersapp.payment_result, name='payment_result'),
    path('product/<int:pk>/price/', ordersapp.get_product_price),
]

    

ordersapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RD'
    CANCEL = 'CNC'
    DELIVERED = 'DVD'
    UNPAID = 'UP'
    PENDING = 'PDG'

    STATUSES = (
        (FORMING, 'Формируется'),
        (SENT_TO_PROCEED, 'Отправлен в обработку'),
        (PROCEEDED, 'Обработан'),
        (PAID, 'Оплачен'),
        (READY, 'Готов к выдаче'),
        (CANCEL, 'Отменен'),
        (DELIVERED, 'Выдан'),
        (UNPAID, 'Не оплачено'),
        (PENDING, 'Идет оплата'),
    )



    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, verbose_name='создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='обновлен')
    is_active = models.BooleanField(default=True)

    status = models.CharField(choices=STATUSES, default=FORMING, verbose_name='статус', max_length=3)

    def get_total_quantity(self):
        _items = self.orderitems.select_related()
        _totalquantity = sum(list(map(lambda x: x.quantity, _items)))
        return _totalquantity

    def get_total_cost(self):
        _items = self.orderitems.select_related()
        _totalcost = sum(list(map(lambda x: x.get_product_cost(), _items)))
        return _totalcost

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()

    @staticmethod
    def get_item(pk):
        return Order.objects.get(pk=pk)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='orderitems')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='количество')

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk)

ordersapp/forms.py
from django import forms
from .models import Order, OrderItem
from mainapp.models import Product



class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)


    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

        self.fields['product'].queryset = Product.objects.all().select_related()

ordersapp/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from ordersapp.models import Order
from django.db import transaction
from django.forms import inlineformset_factory
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.http.response import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.dispatch import receiver
from django.db.models.signals import pre_save, pre_delete
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from basketapp.models import Basket
from ordersapp.models import Order, OrderItem
from ordersapp.forms import OrderItemForm
from mainapp.views import product, Product


class OrderList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, is_active=True)

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(ListView, self).dispatch(*args, **kwargs)

class OrderCreate(CreateView):
   model = Order
   success_url = reverse_lazy('order:list')
   fields = []

   def get_context_data(self, **kwargs):
       data = super().get_context_data(**kwargs)
       OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
       if self.request.POST:
           formset = OrderFormSet(self.request.POST)
       else:
           basket_items = list(Basket.objects.filter(user=self.request.user))
           if len(basket_items):
               OrderFormSet = inlineformset_factory(
                   Order,
                   OrderItem,
                   form=OrderItemForm,
                   extra=len(basket_items)
               )
               formset = OrderFormSet()
               for num, form in enumerate(formset.forms):
                   form.initial['product'] = basket_items[num].product
                   form.initial['quantity'] = basket_items[num].quantity
                   form.initial['price'] = basket_items[num].product.price
               for basket_item in basket_items:
                   basket_item.delete()
           else:
               formset = OrderFormSet()
       data['orderitems'] = formset
       return data

   def form_valid(self, form):
       context = self.get_context_data()
       orderitems = context['orderitems']

       with transaction.atomic():
           Basket.get_items(self.request.user).delete()
           form.instance.user = self.request.user
           self.object = form.save()

           if orderitems.is_valid():
               orderitems.instance = self.object
               orderitems.save()

       if self.object.get_total_cost() == 0:
           self.object.delete()

       return super().form_valid(form)


class OrderUpdate(UpdateView):
    model = Order
    success_url = reverse_lazy('order:list')
    fields = []

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(OrderUpdate, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            data['orderitems'] = OrderFormSet(self.request.POST, instance=self.object)
        else:
            # orderitems_formset = OrderFormSet(instance=self.object)
            queryset = self.object.orderitems.select_related()
            formset = OrderFormSet(instance=self.object, queryset=queryset)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price
            data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            # form.instance.user = self.request.user
            self.object = form.save()

            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super().form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('order:list')

class OrderRead(DetailView):
    model = Order


def forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('order:list'))

@receiver(pre_save, sender=Basket)
@receiver(pre_save, sender=OrderItem)
def products_quantity_update_save(sender, update_fields, instance, **kwargs):
        if instance.pk:
            instance.product.quantity -= instance.quantity - instance.get_item(pk=instance.pk).quantity
        else:
            instance.product.quantity -= instance.quantity

        instance.product.save()

@receiver(pre_delete, sender=Basket)
@receiver(pre_delete, sender=OrderItem)
def products_quantity_update_delete(sender, instance, **kwargs):
        instance.product.quantity += instance.quantity
        instance.product.save()

def payment_result(request):
    # ik_co_id = 51237
    # daa8f2a2d8413000000 & ik_inv_id = 320477108 & \
     # ik_pm_no = ID1
    payment_status = request.GET.get('ik_inv_st')
    if payment_status == 'success':
        order_pk = request.GET.get('ik_pm_no').replace('ID', '')
        order_item = Order.objects.get(pk=order_pk)
        order_item.status = Order.PAID
        order_item.save()
    elif payment_status == 'fail':
        order_pk = request.GET.get('ik_pm_no').replace('ID', '')
        order_item = Order.objects.get(pk=order_pk)
        order_item.status = Order.UNPAID
        order_item.save()
    else:
        order_pk = request.GET.get('ik_pm_no').replace('ID', '')
        order_item = Order.objects.get(pk=order_pk)
        order_item.status = Order.PENDING
        order_item.save()
    return  HttpResponseRedirect(reverse('order:list'))

def get_product_price(request, pk):
    if request.is_ajax():
        product = Product.objects.filter(pk=pk).first()
        if product:
            return JsonResponse({'price': product.price})
        else:
            return JsonResponse({'price': 0})

ordersapp/templates/ordersapp/includes/inc_order_actions.html
{% if object.status == 'FM' %}
   <button class="btn btn-warning btn-round form-control last">
       <a href="{% url 'order:forming_complete' object.pk %}">
           совершить покупку
       </a>
   </button>
   <button class="btn btn-default btn-round form-control last">
       <a href="{% url 'order:delete' object.pk %}">удалить</a>
   </button>
{% endif %}
{% if object.status == 'STP' %}
    <form name="payment" method="post" action="https://sci.interkassa.com/" accept-charset="UTF-8">
          <input type="hidden" name="ik_co_id" value="51237daa8f2a2d8413000000"/>
          <input type="hidden" name="ik_pm_no" value="ID{{ order.pk }}"/>
          <input type="hidden" name="ik_am" value="{{ object.get_total_cost }}"/>
          <input type="hidden" name="ik_cur" value="rub"/>
          <input type="hidden" name="ik_suc_u" value="http://80.78.244.171/order/payment/result/"/>
          <input type="hidden" name="ik_pnd_u" value="http://80.78.244.171/order/payment/result/"/>
          <input type="hidden" name="ik_fal_u" value="http://80.78.244.171/order/payment/result/"/>
          <input type="hidden" name="ik_suc_m" value="get"/>
          <input type="hidden" name="ik_pnd_m" value="get"/>
          <input type="hidden" name="ik_fal_m" value="get"/>
          <input type="hidden" name="ik_desc" value="Платеж из интернет магазина мебели"/>
          <button type="submit" value="Pay" class="btn btn-success form-control last">Оплатить</button>
    </form>
{% endif %}

<button class="btn btn-info btn-round form-control last">
   <a href="{% url 'order:list' %}">
       к списку заказов
   </a>
</button>
<button class="btn btn-default btn-round form-control last">
   <a href="{% url 'main' %}">на главную</a>
</button>

ordersapp/templates/ordersapp/includes/inc_order_summary.html
{% if object %}
   <div class="h2">Заказ №{{ object.pk }} от {{ object.created|date:"Y-m-d H:i:s" }}</div>
   <hr>
   <div class="h4">заказчик: {{ user.last_name }} {{ user.first_name }} </div>
   <div class="h4">обновлен: {{ object.updated|date:"Y-m-d H:i:s" }}</div>
   <div class="h4">cтатус: {{ object.get_status_display }}</div>
   <hr>
    {% with object_summary=object.get_summary %}
       <div class="h4">
           общее количество товаров: <span class="order_total_quantity">{{ object_summary.total_quantity }}</span>
       </div>
       <div class="h3">
           общая стоимость: <span class="order_total_cost">{{ object_summary.total_cost }}</span> руб
       </div>
    {% endwith %}
{% else %}
   <div class="h2">Новый заказ</div>
   <hr>
   <div class="h4">заказчик: {{ user.last_name }} {{ user.first_name }} </div>
   {% if basket.0 %}
       <div class="h4">
           общее количество товаров: <span class="order_total_quantity">{{ basket.0.get_total_quantity }}</span>
       </div>
       <div class="h3">
           общая стоимость: <span class="order_total_cost">{{ basket.0.get_total_cost }}</span> руб
       </div>
   {% endif %}
{% endif %}
<hr> 