authapp/urls.py
# from django.conf.urls import url

import authapp.views as authapp
from django.urls import re_path

app_name="authapp"

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^edit/$', authapp.edit, name='edit'),
    re_path('verify/<email>/<key>/', authapp.verify, name='verify'),
    ]

    

geekshop/urls.py
# from django.conf.urls import *
from django.contrib import admin
import mainapp.views as mainapp

from django.conf import settings
from django.conf.urls.static import static

from django.urls import re_path, path, include

urlpatterns = [
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^products/', include('mainapp.urls', namespace='products')),
    re_path(r'^contact/', mainapp.contact, name='contact'),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
    re_path(r'^admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
# from django.conf.urls import url

import ordersapp.views as ordersapp
from django.urls import path

app_name="ordersapp"

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='list'),
    path('create/', ordersapp.OrderCreate.as_view(), name='create'),
    path('update/<pk>/', ordersapp.OrderUpdate.as_view(), name='update'),
    path('delete/<pk>/', ordersapp.OrderDelete.as_view(), name='delete'),
    path('read/<pk>/', ordersapp.OrderRead.as_view(), name='read'),
    path('forming/complete/<pk>/', ordersapp.forming_complete, name='forming_complete'),

    path('payment/result/', ordersapp.payment_result, name='payment_result'),
    path('product/<int:pk>/price/', ordersapp.get_product_price),
]

    

ordersapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RD'
    CANCEL = 'CNC'
    DELIVERED = 'DVD'
    UNPAID = 'UP'
    PENDING = 'PDG'

    STATUSES = (
        (FORMING, 'Формируется'),
        (SENT_TO_PROCEED, 'Отправлен в обработку'),
        (PROCEEDED, 'Обработан'),
        (PAID, 'Оплачен'),
        (READY, 'Готов к выдаче'),
        (CANCEL, 'Отменен'),
        (DELIVERED, 'Выдан'),
        (UNPAID, 'Не оплачено'),
        (PENDING, 'Идет оплата'),
    )



    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, verbose_name='создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='обновлен')
    is_active = models.BooleanField(default=True)

    status = models.CharField(choices=STATUSES, default=FORMING, verbose_name='статус', max_length=3)

    def get_total_quantity(self):
        _items = self.orderitems.select_related()
        _totalquantity = sum(list(map(lambda x: x.quantity, _items)))
        return _totalquantity

    def get_total_cost(self):
        _items = self.orderitems.select_related()
        _totalcost = sum(list(map(lambda x: x.get_product_cost(), _items)))
        return _totalcost

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()

    @staticmethod
    def get_item(pk):
        return Order.objects.get(pk=pk)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='orderitems')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='количество')

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk)

ordersapp/forms.py
from django import forms
from .models import Order, OrderItem
from mainapp.models import Product



class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)


    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

        self.fields['product'].queryset = Product.objects.all().select_related()

ordersapp/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from ordersapp.models import Order
from django.db import transaction
from django.forms import inlineformset_factory
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.http.response import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.dispatch import receiver
from django.db.models.signals import pre_save, pre_delete
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from basketapp.models import Basket
from ordersapp.models import Order, OrderItem
from ordersapp.forms import OrderItemForm
from mainapp.views import product, Product


class OrderList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, is_active=True)

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(ListView, self).dispatch(*args, **kwargs)

class OrderCreate(CreateView):
   model = Order
   success_url = reverse_lazy('order:list')
   fields = []

   def get_context_data(self, **kwargs):
       data = super().get_context_data(**kwargs)
       OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
       if self.request.POST:
           formset = OrderFormSet(self.request.POST)
       else:
           basket_items = list(Basket.objects.filter(user=self.request.user))
           if len(basket_items):
               OrderFormSet = inlineformset_factory(
                   Order,
                   OrderItem,
                   form=OrderItemForm,
                   extra=len(basket_items)
               )
               formset = OrderFormSet()
               for num, form in enumerate(formset.forms):
                   form.initial['product'] = basket_items[num].product
                   form.initial['quantity'] = basket_items[num].quantity
                   form.initial['price'] = basket_items[num].product.price
               for basket_item in basket_items:
                   basket_item.delete()
           else:
               formset = OrderFormSet()
       data['orderitems'] = formset
       return data

   def form_valid(self, form):
       context = self.get_context_data()
       orderitems = context['orderitems']

       with transaction.atomic():
           Basket.get_items(self.request.user).delete()
           form.instance.user = self.request.user
           self.object = form.save()

           if orderitems.is_valid():
               orderitems.instance = self.object
               orderitems.save()

       if self.object.get_total_cost() == 0:
           self.object.delete()

       return super().form_valid(form)


class OrderUpdate(UpdateView):
    model = Order
    success_url = reverse_lazy('order:list')
    fields = []

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(OrderUpdate, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            data['orderitems'] = OrderFormSet(self.request.POST, instance=self.object)
        else:
            # orderitems_formset = OrderFormSet(instance=self.object)
            queryset = self.object.orderitems.select_related()
            formset = OrderFormSet(instance=self.object, queryset=queryset)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price
            data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            # form.instance.user = self.request.user
            self.object = form.save()

            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super().form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('order:list')

class OrderRead(DetailView):
    model = Order


def forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('order:list'))

@receiver(pre_save, sender=Basket)
@receiver(pre_save, sender=OrderItem)
def products_quantity_update_save(sender, update_fields, instance, **kwargs):
        if instance.pk:
            instance.product.quantity -= instance.quantity - instance.get_item(pk=instance.pk).quantity
        else:
            instance.product.quantity -= instance.quantity

        instance.product.save()

@receiver(pre_delete, sender=Basket)
@receiver(pre_delete, sender=OrderItem)
def products_quantity_update_delete(sender, instance, **kwargs):
        instance.product.quantity += instance.quantity
        instance.product.save()

def payment_result(request):
    # ik_co_id = 51237
    # daa8f2a2d8413000000 & ik_inv_id = 320477108 & \
     # ik_pm_no = ID1
    payment_status = request.GET.get('ik_inv_st')
    if payment_status == 'success':
        order_pk = request.GET.get('ik_pm_no').replace('ID', '')
        order_item = Order.objects.get(pk=order_pk)
        order_item.status = Order.PAID
        order_item.save()
    elif payment_status == 'fail':
        order_pk = request.GET.get('ik_pm_no').replace('ID', '')
        order_item = Order.objects.get(pk=order_pk)
        order_item.status = Order.UNPAID
        order_item.save()
    else:
        order_pk = request.GET.get('ik_pm_no').replace('ID', '')
        order_item = Order.objects.get(pk=order_pk)
        order_item.status = Order.PENDING
        order_item.save()
    return  HttpResponseRedirect(reverse('order:list'))

def get_product_price(request, pk):
    if request.is_ajax():
        product = Product.objects.filter(pk=pk).first()
        if product:
            return JsonResponse({'price': product.price})
        else:
            return JsonResponse({'price': 0})

ordersapp/templates/ordersapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/jquery.formset.js' %}"></script>
        <script src="{% static 'js/order_scripts.js' %}"></script>
    {% endblock %}
</head>
<body>
	<div class="basket_container">

        {% block content %}

        {% endblock %}

	</div>
</body>
</html>

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block content %}
   <div class="category_delete">
       <div class="h1">Уверены, что хотите удалить?</div>
       {% include 'ordersapp/includes/inc_order_summary.html' %}
       <form action="{% url 'order:delete' object.pk %}" method="post">
           {% csrf_token %}
           <input class="btn btn-danger" type="submit" value="удалить">
       </form>
       <button class="btn btn-success">
           <a href="{% url 'order:list' %}">отмена</a>
       </button>
   </div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "ordersapp/base.html" %}
{% load static %}
{% load my_tags %}

{% block content %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="basket_list">
       {% for item in object.orderitems.select_related %}
           <div class="basket_record">
               <img src="{{ item.product.image|media_folder_products }}"
                    alt="{{ item.product.short_desc }}">
               <span class="category_name">
                   {{ item.product.category.name }}
               </span>
               <span class="product_name">{{ item.product.name }}</span>
               <span class="product_price">
                   {{ item.product.price }}&nbspруб
               </span>
               <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
               <span class="total_product_cost">
                    = {{ item.get_product_cost }}&nbspруб
               </span>
           </div>
       {% endfor %}
   </div>
   {% include 'ordersapp/includes/inc_order_actions.html' %}

{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load static %}
{% load cache %}

{% block content %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="order_form">
       <form action="" method="post">
           {% csrf_token %}
           {{ form.as_p }}
           <table class="table">
               {{ orderitems.management_form }}
               {% for form in orderitems.forms %}
                   {% if forloop.first %}
                       <thead>
                       <tr>
                           {% for field in form.visible_fields %}
                               <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                   {{ field.label|capfirst }}
                               </th>
                           {% endfor %}
                       </tr>
                       </thead>
                   {% endif %}
                   <tr class="formset_row">
                       {% for field in form.visible_fields %}
                           <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                               {% if forloop.first %}
                             {% for hidden in form.hidden_fields %}
                                       {{ hidden }}
                                   {% endfor %}
                               {% endif %}
                               {{ field.errors.as_ul }}
                               {% if field.name != 'price' %}
                                    {% if field.name == 'product' %}
                                        {% cache 3600 orderitemform_product field.value %}
                                            {{ field }}
                                        {% endcache %}
                                    {% else %}
                                        {{ field }}
                                    {% endif %}
                               {% else %}
                                    {% if field.value %}
                                    <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">
                                        {{ field.value|default:" " }}
                                      </span> руб
                                    {% endif %}
                               {% endif %}
                           </td>
                       {% endfor %}
                   </tr>
               {% endfor %}
           </table>
           <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить</button>
           {% include 'ordersapp/includes/inc_order_actions.html' %}
       </form>
   </div>

{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block content %}
      <div class="text-center h2 header">
        Ваши заказы, {% if user.first_name %}{{ user.first_name }}{% else %}Пользователь{% endif %}
      </div>

      <table class="table">
        <thead>
          <th>ID</th>
          <th>Создан</th>
          <th>Обновлен</th>
          <th>Статус</th>
        </thead>
        <tbody>
          {% for item in object_list %}
            <tr>
                <td>{{ item.pk }}</td>
                <td>{{ item.created|date:"d.m.Y H:i:s" }}</td>
                <td>{{ item.updated|date:"d.m.Y H:i:s" }}</td>
                <td>{{ item.get_status_display }}</td>
                <td>
                    <a class="btn btn-link" href="{% url 'order:read' item.pk %}">посмотреть</a>
                </td>
                <td>
                    {% if item.status == 'FM' %}
                    <a class="btn btn-link" href="{% url 'order:update' item.pk %}">изменить</a>
                    {% endif %}
                </td>
                <td>
                    {% if item.status == 'FM' %}
                    <a class="btn btn-link" href="{% url 'order:delete' item.pk %}">удалить</a>
                    {% endif %}
                </td>
            </tr>
          {% endfor %}
        </tbody>
        <a href="{% url 'order:create' %}" class="btn btn-primary">новый заказ</a>
        <hr>
        <a href="{% url 'main' %}" class="btn btn-link">на главную</a>
      </table>
{% endblock %}